name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: temurin
    - name: Build with Maven (skip minify)
      run: mvn package -Dminify.skip=true
    - name: staging
      run: mkdir staging && cp target/*.war staging
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
