name: Java CI with Maven

on:
  push:
    branches: [ "main", "develop" ] # Trigger on pushes to main and develop branches
  pull_request:
    branches: [ "main", "develop" ] # Trigger on pull requests targeting main and develop

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Specify the Java version. You can change this to '11', '21', etc.
          distribution: 'temurin' # Recommended distribution for OpenJDK
          cache: maven # Cache Maven dependencies to speed up builds

      - name: Build with Maven
        run: mvn -B package --file pom.xml # Command to build your Maven project

      - name: Run Maven Tests
        run: mvn -B test --file pom.xml # Command to run your Maven tests

      # Optional: Upload build artifacts (e.g., JAR/WAR files)
      - name: Upload a build artifact
        uses: actions/upload-artifact@v4
        with:
          name: your-app-artifact
          path: target/*.jar # Adjust this path to your actual artifact (e.g., target/*.jar, target/*.war)
          retention-days: 5 # How long to keep the artifact (optional)

 
