name: Build Virtual Judge WAR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Install plexus-utils manually (for minify plugin)
      run: |
        mvn dependency:get -Dartifact=org.codehaus.plexus:plexus-utils:3.3.0

    - name: Build WAR package with Maven
      run: mvn -B clean package --file pom.xml

    - name: Archive WAR
      uses: actions/upload-artifact@v4
      with:
        name: virtual-judge.war
        path: target/virtual-judge.war
